### ISSUE TITLE
[플랫폼관리>호스트관리] 가상화 자원현황 디스크 총량 초과 표시

### ISSUE THREAD

**Issue by dheekim** [leedaepyeong/HCOA#1]
[사전조건]
- 가상화 자원 디스크 : 임계치 전체 쓰기

[절차]
1. 관리자 로그인
2. 대시보드 > 가상리소스 현황 > 작업명 선택
3. 플랫폼 관리 > 컴퓨팅 관리 > 호스트 관리 메뉴 진입
4. 가상화 자원 현황 > 디스크 가상화율 확인

[수행결과]
- 디스크가 사용율이 총량을 초과하여 표시됨

[기대사항]
- 디스크 사용율 정확하게 표시

![image](https://user-images.githubusercontent.com/52692342/68365920-5362b280-0175-11ea-9757-dab45bcfc287.png)

**Comment by gustnor** [comment]
[원인]
디스크 총량 계산이 호스트별 디스크 총량 합이 아닌 1개 호스트의 총량값만 사용함

[조치사항]
디스크 총량 계산을 호스트별 디스크 총량 합으로 변경

[참고사항]
해당 문제는 플랫폼(ceph) 구성방법에 따라 오류 일수도 있고, 아닐 수도 있음
플랫폼 구성에 일관성 필요
