### ISSUE TITLE
[가상화 서비스>가상 서버>인스턴스]중지 버튼 미동작

### ISSUE THREAD

**Issue by dheekim** [leedaepyeong/HCOA#11]
[사전조건]
인스턴스 생성

[절차]
1. 관리자 로그인
2. 가상화 서비스 > 가상서버 > 인스턴스 화면 진입
3. 인스턴스 생성 > 관리 선택박스 선택 > 중지 선택

[수행결과]
오류 토스트팝업 노출되며 중지되지 않음

[기대사항]
인스턴스 중지됨

![image](https://user-images.githubusercontent.com/52692553/68647624-b3849a80-0561-11ea-917c-8f33ce78f922.png)

**Comment by gustnor** [comment]
[원인]
인스턴스가 스냅샷 진행중이면 상태는 active를 유지하고, task 상태만 변경이 되는데, 이상태에서는 인스턴스에 대한 action을 수행 할 수 없음

[조치 결과]
인스턴스의 task 상태에 값이 있으면 인스턴스에 대한 action을 수행 할 수 없게 로직 추가
