### ISSUE TITLE
[가상화서비스>인스턴스] 디폴트 보안그룹 제외하고 인스턴스 생성시 디폴트 보안그룹 자동적용됨

### ISSUE THREAD

**Issue by leedaepyeong** [leedaepyeong/HCOA#12]
[사전조건]
보안그룹 신규 생성

[절차]
1. 관리자 로그인
2.  가상화서비스 > 인스턴스  화면 진입
3. 추가버튼 선택
4. 보안그룹 디폴트 제외, 신규 추가
5. 필수값 입력
6. 인스턴스 생성버튼 선택
7. 생성된 인스턴스 보안그룹 확인

[수행결과]
디폴트 및 신규 보안그룹 적용됨

[기대사항]
신규 보안그룹만 적용됨

**Comment by gustnor** [comment]
[원인]
포털 내부적으로 포트 만들고, 인스턴스를 생성을 하는데, 
포트 생성 시점에 default 보안그룹은 자동으로 적용됨

사용자 편의상 default 보안그룹은 인스턴스 생성 시점에 적용되는게 맞다고 생각됨

**Comment by leedaepyeong** [comment]
인스턴스 생성시 디폴트 그룹을 해지할수 있는 동작이 있어서 오해가 생기는것같습니다.
생성화면에서 디폴트그룹은 해지되지 않도록 변경해야될것같습니다.

**Comment by yrimjang** [comment]
[조치사항]
인스턴스 생성 - 보안그룹 설정 시 디폴트그룹은 해지되지 않도록 수정함

**Comment by leedaepyeong** [comment]
확인하였습니다.
