### ISSUE TITLE
[가상화서비스>스냅샷] 스냅샷으로부터 인스턴스 생성화면 진입시 사양선택 불가 현상

### ISSUE THREAD

**Issue by leedaepyeong** [leedaepyeong/HCOA#14]
[사전조건]
스냅샷 생성

[절차]
1. 관리자 로그인
2. 가상화 서비스 > 가상서버 > 스냅샷 화면 진입
3. 스냅샷 관리 > 인스턴스 생성 선택
4. 사양 선택

[수행결과]
사양선택 로딩이 완료되지 않으며 선택 불가함

[기대사항]
 선택한 사양이 선택됨

![image](https://user-images.githubusercontent.com/52692342/68721662-6ef70e80-05f6-11ea-9984-e4f293d4cacc.png)

**Comment by gustnor** [comment]
[원인]
iaas-api 변경분 미반영

[조치 내용]
조회 데이터 array size 체크 로직 삭제

**Comment by leedaepyeong** [comment]
사양선택 및 스냅샷을 통한 인스턴스 생성확인하였습니다.
