### ISSUE TITLE
[가상화서비스>인스턴스] 인스턴스 에러 상태에서 스냅샷 메뉴 활성화 되어 있음

### ISSUE THREAD

**Issue by leedaepyeong** [leedaepyeong/HCOA#16]
[사전조건]
인스턴스 오류 상태

[절차]
1. 관리자 로그인
2. 가상화서비스 > 가상서버 > 인스턴스 화면 진입
3. 관리메뉴 > 스냅샷 선택
4. 스냅샷 필수값 값입력
5. 생성버튼 선택

[수행결과]
 오류 토스트팝업 노출되며 스냅샷 미생성됨

[기대사항]
인스턴스 오류 상태에서는 스냅샷 생성 메뉴 비활성화 처리됨

**Comment by gustnor** [comment]
[조치 내용]
인스턴스 상태별 action 재정의 및 코드 반영

**Comment by leedaepyeong** [comment]
스냅샷 생성 확인하였습니다.
