### ISSUE TITLE
[가상화서비스>인스턴스] 인스턴스명 최대글자 입력 생성시 노출 오류

### ISSUE THREAD

**Issue by leedaepyeong** [leedaepyeong/HCOA#17]
[사전조건]
없음

[절차]
1. 관리자 로그인
2. 가상화서비스 > 가상서버 > 인스턴스 화면 진입
3. 생성서븐 선택
4. 인스턴스명 최대길이 입력
5. 우측 기본정보 확인

[수행결과]
인스턴스 이름과 절취선이 겹쳐서 노출됨

[기대사항]
절취선 개행 높이에 맞게 위치변경되어 노출됨

![image](https://user-images.githubusercontent.com/52692342/68742091-a5eb1580-0632-11ea-8ebb-9ead3a435e47.png)

**Comment by yrimjang** [comment]
[조치사항]
인스턴스 생성시 이름 최대 글자수는 20으로 나타나는데 입력은 50까지 됨
입력 글자수 50 -> 20으로 변경함

**Comment by leedaepyeong** [comment]
확인하였습니다.
