### ISSUE TITLE
[가상화서비스>대시보드] 가상서버현황 "디스크" 컬럼명 변경 필요

### ISSUE THREAD

**Issue by leedaepyeong** [leedaepyeong/HCOA#18]
[사전조건]
없음

[절차]
1. 관리자 로그인
2. 가상화서비스 > 대시보드 화면 진입
3. 가상서버 현황 컬럼값 확인

[수행결과]
"디스크" 컬럼명 노출됨

[기대사항]
"OS디스크" 컬럼명 노출됨
인스턴스 생성시 노출 컬럼과 동일하게 맞춰야함

![image](https://user-images.githubusercontent.com/52692342/68742528-bbad0a80-0633-11ea-8cca-5a094c01fc5e.png)

**Comment by yrimjang** [comment]
가상화서비스 > 대시보드 > 가상화 자원 사용 현황 컬럼명
"디스크" -> "볼륨"  으로 수정

가상화서비스 > 대시보드 > 가상 서버 현황 컬럼명 
"디스크" > "OS디스크"로 수정

**Comment by leedaepyeong** [comment]
확인하였습니다.
