### ISSUE TITLE
[가상화서비스>가상LB] 라운드로빈 이외 알고리즘 비중설정 불필요함

### ISSUE THREAD

**Issue by leedaepyeong** [leedaepyeong/HCOA#19]
[사전조건]
인스턴스 생성
LB 생성

[절차]
1. 관리자 로그인
2. 가상화서비스 > 가상네트워크 관리 > 가상LB > 가상LB 상세 화면 진입
3. 라운드 로빈 이외 알고리즘으로 포트 추가
4. 서비스 연결 추가 완료
5. 연결관리 > 연결서비스 수정 메뉴 선택
6. 팝업내 비중 컬럼 확인

[수행결과]
비중 컬럼 노출됨

[기대사항]
 라운드로빈 이외 알고리즘 비중 컬럼 미노출됨

**Comment by yrimjang** [comment]
[가상LB > LB포트관리 > 서비스 연결 추가]
알고리즘이 라운드 로빈일 때에만 비중을 설정할 수 있도록 수정함

[가상LB > LB 포트관리 > 연결 관리]
알고리즘이 라운드 로빈일 때에만 연결 서비스 수정 메뉴가 활성화되도록 수정함

**Comment by leedaepyeong** [comment]
확인하였습니다.
