### ISSUE TITLE
[플랫폼관리>이미지관리] 메모리 단위 수정 필요

### ISSUE THREAD

**Issue by dheekim** [leedaepyeong/HCOA#2]
[사전조건]
- 이미지 생성시 최소메모디 테라급으로 부여

[절차]
1. 관리자 로그인
2. 대시보드 > 가상리소스 현황 > 작업명 선택
3. 플랫폼 관리 > 컴퓨팅 관리 > 이미지 관리
4. 이미지 목록 확인

[수행결과]
최소 메모리 값 단위가 TB로 표시됨 (GB가 옳은 값으로 보임)
추가로 이미지 수정시에 최소 메모리의 단위도 MB가 아니라 KB가 옳은 단위로 보임

[기대사항]
최소 메모리 단위 수정됨

**Comment by gustnor** [comment]
오류 원인은 DB에 저장시 단위처리를 잘못해서 발생
최소 메모리값의 기본 단위는 MB이고, 
입력값에 따라 화면에 표시는 최소 메모리는 MB/GB/TB가 혼용되서 표시됨
