### ISSUE TITLE
[가상화서비스>가상LB] LB 포트 추가시 LB 알고리즘,헬스체크유형 값 미노출 현상

### ISSUE THREAD

**Issue by leedaepyeong** [leedaepyeong/HCOA#20]
[사전조건]
인스턴스 생성
LB 생성

[절차]
1. 관리자 로그인
2. 가상화서비스 > 가상네트워크 관리 > 가상LB > 가상LB 상세 화면 진입
3. LB 포트 추가
4. 목록 확인

[수행결과]
LB 알고리즘,헬스체크유형 값 미노출됨
화면 새로고침시 노출됨

[기대사항]
LB 알고리즘,헬스체크유형 값 노출됨

![image](https://user-images.githubusercontent.com/52692342/68838545-2593e580-0702-11ea-8745-c2805761be66.png)

**Comment by gustnor** [comment]
[조치 내용]
LB 풀과 모니터가 생성될때까지  LB 포트 조회

**Comment by leedaepyeong** [comment]
추후 재현시 재등록하겠습니다.
