### ISSUE TITLE
[사용자 > 개인정보 수정] 회원탈퇴 버튼 미동작됨

### ISSUE THREAD

**Issue by dheekim** [leedaepyeong/HCOA#24]
[사전조건]
사용자 계정 생성

[절차]
1. 사용자 로그인
2. 개인정보 수정 > 회원탈퇴 버튼 선택
3. 메시지 팝업 노출 확인 > "예" 선택

[수행결과]
"401" 토스트 팝업 노출되며 회원탈퇴 버튼 미동작됨

[기대사항]
회원탈퇴 버튼 동작됨

![image](https://user-images.githubusercontent.com/52692553/68918209-9d204e00-07b0-11ea-8178-c0d960c9229b.png)

**Comment by gustnor** [comment]
[원인]
사용자 삭제 api 파라미터 오류

[조치 내용]
사용자 삭제 api 호출시 사용하는 파라미터를  사용자 uuid에서 사용자 id로 변경
