### ISSUE TITLE
[플랫폼관리>마이그레이션] 정지된 호스트로 마이그레이션시 인스턴스 에러 발생함

### ISSUE THREAD

**Issue by leedaepyeong** [leedaepyeong/HCOA#25]
[사전조건]
호스트 4번 정지 상태
호스트 3번 인스턴스 생성상태

[절차]
1. 관리자 로그인
2. 플랫폼관리 > 첨퓨팅 관리 > 마이그레이션 진입
3. 호스트3번 인스턴스 호스트4번으로 마이그레이션 동작
4. 인스턴스 상태 확인

[수행결과]
마이그레이션 완료 메시지는 노출됨
호스트 확인시 이동되지 않음
인스턴스 상태 에러상태로 노출됨

[기대사항]
마이그레이션 정상동작함
인스턴스 정상 상태로 노출됨

![image](https://user-images.githubusercontent.com/52692342/68918408-5b43d780-07b1-11ea-8b65-d3b23f96cc89.png)

**Comment by gustnor** [comment]
[원인]
정지된 호스트로는 마이그레이션이 불가한데 마이그레이션 action을 수행하면서 오류 발생

[조치 내용]
#31 이슈 반영으로 정지된 호스트로는 마이그레이션 불가능함

**Comment by leedaepyeong** [comment]
확인하였습니다.
