### ISSUE TITLE
[플랫폼관리>마이그레이션] 오류상태 인스턴스 복구시 로딩이 종료되지 않음

### ISSUE THREAD

**Issue by leedaepyeong** [leedaepyeong/HCOA#26]
[사전조건]
인스턴스 오류상태

[절차]
1. 관리자 로그인
2. 플랫폼관리 > 첨퓨팅 관리 > 마이그레이션 진입
3. 오류 발생 인스턴스 관리메뉴 > 상태변경 메뉴 선택
4. 팝업 확인 선택
5. 로딩 완료 대기

[수행결과]
로딩이 완료되지 않음
다른 윈도우창으로 인스턴스 확인시 정상상태로 복구됨

[기대사항]
로딩완료됨
![image](https://user-images.githubusercontent.com/52692342/68918601-2b490400-07b2-11ea-8c2d-7362317c7097.png)

**Comment by yrimjang** [comment]
[원인]
상태 변경 성공시 로딩바 종료 로직을 적용하지 않음
[조치]
상태 변경 성공시 로딩바 종료 로직을 적용시킴

**Comment by leedaepyeong** [comment]
확인하였습니다.
