### ISSUE TITLE
[가상화서비스] 테넌트삭제시 삭제된 테넌트 정보 노출됨

### ISSUE THREAD

**Issue by leedaepyeong** [leedaepyeong/HCOA#29]
[사전조건]
작업(테넌트) 생성

[절차]
1. 관리자 로그인
2. 작업(테넌트) 선택
3. 플랫폼관리> 테넌트관리 > 잡업관리  화면 진입
4. 절차2에서 진입한 작업 삭제
5. 가상화서비스 > 대시보드 화면 진입

[수행결과]
삭제한 작업 대시보드 노출됨

[기대사항]
삭제한 작업 대시보드 미노출됨

**Comment by gustnor** [comment]
[원인]
left 메뉴 이동시 선택된 테넌트 정보를 클리어 하지 않음

[조치 내용]
대시보드/가상화 서비스/플랫폼  관리 메뉴간 이동 시 선택된 테넌트 정보 삭제

**Comment by leedaepyeong** [comment]
확인하였습니다.
