### ISSUE TITLE
[가상화서비스>네트워크] LB 연결된 IP 인스턴스 링크 동작 정의 필요

### ISSUE THREAD

**Issue by leedaepyeong** [leedaepyeong/HCOA#30]
[사전조건]
LB 생성

[절차]
1. 관리자 로그인
2. 가상화서비스 > 가상네트워크  > 네트워크 화면 진입
3. LB가 생성된 네트워크 대역 선택
4. 인스턴스 > LB 링크 선택

[수행결과]
빈 인스턴스 페이지 이동됨

[기대사항]
링크에 대한 정의 필요

![image](https://user-images.githubusercontent.com/52692342/69130019-17bfd500-0af3-11ea-93b3-7e53de2f8f5d.png)

**Comment by gustnor** [comment]
[조치 내용]
네트워크 포트 정보 조회시 vmType(VM/LB/INVALID) 항목 추가
vmType에 따라 다른 링크 연결

**Comment by leedaepyeong** [comment]
확인하였습니다.
