### ISSUE TITLE
[플랫폼관리>마이그레이션] 마이그레이션 타켓 다른 존 호스트 노출됨

### ISSUE THREAD

**Issue by leedaepyeong** [leedaepyeong/HCOA#31]
[사전조건]
존 2개 이상
존 별  호스트 2개 이상
인스턴스 생성

[절차]
1. 관리자 로그인
2. 플랫폼관리 > 컴퓨팅관리 > 마이그레이션 화면 진입
3. 관리메뉴 > 마이그레이션 선택
4. 타켓호스트 확인

[수행결과]
전체 호스트 노출됨
다른존 호스트 타겟 이동시 같은존 호스트로 이동함

[기대사항]
같은 존으로 설정된 호스트만 노출되어야함

**Comment by gustnor** [comment]
[조치 내용]
마이그레이션 시 가용성존 고정 후 타겟 호스트 선택
라이브 마이그레이션은 가용성존 선택 후 타겟 호스트 선택

**Comment by leedaepyeong** [comment]
확인하였습니다.
