### ISSUE TITLE
[플랫폼관리>쿼터관리] 검색어 입력시 목록 미노출됨

### ISSUE THREAD

**Issue by leedaepyeong** [leedaepyeong/HCOA#35]
[절차]
1. 관리자 로그인
2. 플랫폼관리 > 테넌트관리 > 쿼터관리 화면 진입
3. 검색어 입력

[수행결과]
검색어 매칭되는 검색어 입력에도 목록 미노출됨

[기대사항]
검색어에 매칭되는 목록 노출됨

**Comment by gustnor** [comment]
[조치 내용]
쿼터 검색 필터 코드 오류 수정

**Comment by leedaepyeong** [comment]
확인하였습니다.
