### ISSUE TITLE
[플랫관리>태넌트 네트워크 관리] 테넌트관리자가 생성한 이름으로 관리자 화면에서 노출되지 않음

### ISSUE THREAD

**Issue by dheekim** [leedaepyeong/HCOA#4]
[사전조건]
- 테넌트관리자 > 네트워크 생성

[절차1]
1. 관리자 로그인
2. 플랫폼 관리 > 네트워크 관리 > 테넌트 네트워크 관리
3. 테넌트가 생성한 네트워크명 확인

[수행결과]
테넌트관리자가 생성한 이름으로 노출되지 않음
- 아토결과와 다르게 QA에서 확인시 재현되지 않음

[기대 사항]
테넌트관리자가 생성한 이름으로 노출됨

![image](https://user-images.githubusercontent.com/52692342/68367061-1d72fd80-0178-11ea-95d5-81d2c1868da0.png)

**Comment by leedaepyeong** [comment]
결함 등록전 수정이 완료되어 즉시 결함종료 처리합니다.
