### ISSUE TITLE
[플랫폼관리>테넌트네트워크관리] 오픈스택용어로 일부 용어 변경 필요

### ISSUE THREAD

**Issue by dheekim** [leedaepyeong/HCOA#5]
[사전조건]
없음

[절차]
1. 관리자 로그인
2. 플랫폼 관리 > 네트워크 관리 > 태넌트 네트워크 관리 화면 진입
3. 용어 확인

[수행결과]
오픈스택과 다른 용어 사용 - 작업, 프로젝트

[기대사항]
오픈스택과 같은 용어 사용 - 도메인, 프로젝트

**Comment by gustnor** [comment]
[조치 사항]
오픈스택에 생성된 네트워크명이 아닌 포털  DB에서 관리하는 네트워크 설명을 네트워크명으로 표시함
