### ISSUE TITLE
[플랫폼관리>대시보드] 컨트롤러 영역 vCPU 용어 수정 필요

### ISSUE THREAD

**Issue by dheekim** [leedaepyeong/HCOA#6]
[사전조건]
없음

[절차]
1. 관리자 로그인
2. 플랫폼 관리 > 대시보드 화면 진입
3. 컨트롤러 컬럼값 화깅ㄴ

[수행결과]
vcpu 용어 노출됨

[기대사항]
cpu 용어 노출됨

**Comment by leedaepyeong** [comment]
결함 등록전 수정이 완료되어 즉시 결함종료 처리합니다.
