### ISSUE TITLE
[플랫폼관리>사용자관리] 관리자 권한변경시 오류 발생함

### ISSUE THREAD

**Issue by leedaepyeong** [leedaepyeong/HCOA#7]
[사전조건]
사용자 생성

[절차]
1. 관리자 로그인
2. 플랫폼 관리 > 사용자관리 관리 화면 진입
3. 관리 드롭박스 > 권한변경 메뉴 선택
4. 팝업 > 역할 관리자 선택
5. 변경 버튼 선택

[수행결과]
오류 토스트팝업 노출되며 권한변경되지 않음

[기대사항]
관리자 권한 변경됨

![image](https://user-images.githubusercontent.com/52692342/68643724-f476b200-0555-11ea-89d9-e2d28454e41a.png)

**Comment by gustnor** [comment]
[원인]
사용자 생성 시 권한 부여 로직이 skip되어 권한 정보가 생성되지 않았고, 권한 변경시 정보가 없어 exception 발생

[조치 내용]
사용자 생성 시 권한 부여 로직 수행

**Comment by leedaepyeong** [comment]
관리자 권한 설정 변경 및 접속시 권리자 메뉴 노출 확인하였습니다.
